# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file# .github/dependabot.yml
version: 2
updates:
  # Ha nincs szükséged `npm` frissítésekre, ezt a részt ki lehet kommentelni vagy eltávolítani
  # - package-ecosystem: "npm" # npm, pip, maven, etc.
  #   directory: "/" # a projekt gyökérkönyvtára
  #   schedule:
  #     interval: "weekly" # lehet daily, weekly vagy monthly

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"

