CREATE TABLE IF NOT EXISTS police_relations (
    police_id SERIAL PRIMARY KEY,
    botnet_id INT,
    crimes_id INT,
    criminals_id INT,
    cybercriminals_id INT,
    detectives_id INT,
    locations_id INT,
    policeofficers_id INT,
    policestation_id INT,
    realtime_id INT,
    simulation_id INT,
    victims_id INT,
    FOREIGN KEY (botnet_id) REFERENCES botnet(id),
    FOREIGN KEY (crimes_id) REFERENCES crimes(id),
    FOREIGN KEY (criminals_id) REFERENCES criminals(id),
    FOREIGN KEY (cybercriminals_id) REFERENCES cybercriminals(id),
    FOREIGN KEY (detectives_id) REFERENCES detectives(id),
    FOREIGN KEY (locations_id) REFERENCES locations(id),
    FOREIGN KEY (policeofficers_id) REFERENCES policeofficers(id),
    FOREIGN KEY (policestation_id) REFERENCES policestation(id),
    FOREIGN KEY (realtime_id) REFERENCES realtime(id),
    FOREIGN KEY (simulation_id) REFERENCES simulation(id),
    FOREIGN KEY (victims_id) REFERENCES victims(id)
);
