-- 04_recipeid_migration.sql
-- recipeid mező átalakítása SERIAL → IDENTITY

-- 1. Sequence szinkronizálása (csak ha még nem futott le)
SELECT setval(pg_get_serial_sequence('receptek', 'receptid'), MAX(receptid));

-- 2. SERIAL default eltávolítása
ALTER TABLE receptek
ALTER COLUMN receptid DROP DEFAULT;

-- 3. Átállás IDENTITY-re
ALTER TABLE receptek
ALTER COLUMN receptid ADD GENERATED BY DEFAULT AS IDENTITY;
